### ISSUE TITLE
mapper.fit_transform() fails

### ISSUE THREAD

**Issue by dolaameng** [scikit-learn-contrib/sklearn-pandas#3]
I was following the tutorial in the readme page. 

``` python
from sklearn import preprocessing, decomposition, linear_model, pipeline, metrics
import sklearn_pandas
import pandas as pd
import numpy as np

mapper = sklearn_pandas.DataFrameMapper([
        ('pet', preprocessing.LabelBinarizer()), 
        ('children', preprocessing.StandardScaler())
])
data = pd.DataFrame({'pet': ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                     'children': [4., 6, 3, 3, 2, 3, 5, 4],
                     'salary':   [90, 24, 44, 27, 32, 59, 36, 27]})
mapper.fit_transform(data)
```

The result:

```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-bd0a8637dc9d> in <module>()
      1 ## we can use the mapper's fit_transform shrotcut to both fit the model
      2 ## and see what transformed data looks like.
----> 3 mapper.fit_transform(data)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/base.pyc in fit_transform(self, X, y, **fit_params)
    406         if y is None:
    407             # fit method of arity 1 (unsupervised transformation)
--> 408             return self.fit(X, **fit_params).transform(X)
    409         else:
    410             # fit method of arity 2 (supervised transformation)

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn_pandas/__init__.pyc in fit(self, X, y)
     44                 transformer.fit(X[columns], y)
     45             except TypeError:
---> 46                 transformer.fit(X[columns])
     47         return self
     48 

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/preprocessing/label.pyc in fit(self, y)
    239             self.indicator_matrix_ = y_type == 'multilabel-indicator'
    240 
--> 241         self.classes_ = unique_labels(y)
    242 
    243         return self

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/utils/multiclass.pyc in unique_labels(*ys)
     96     _unique_labels = _FN_UNIQUE_LABELS.get(label_type, None)
     97     if not _unique_labels:
---> 98         raise ValueError("Unknown label type")
     99 
    100     ys_labels = set(chain.from_iterable(_unique_labels(y) for y in ys))

ValueError: Unknown label type
```

**Comment by chanansh** [comment]
Hi, I still have issues with a similar Error.
Can you please say what's wrong?
```
imputedData = 
	A1	A2	A3	A4	A5	A6	A7	A8	A9	A10	A11	A12	A13	A14	A15
0	b	3083.0	0.0	u	g	w	v	125.0	t	t	1	f	g	202.0	0
1	a	5867.0	446.0	u	g	q	h	304.0	t	t	6	f	g	43.0	560
2	a	245.0	5.0	u	g	q	h	15.0	t	f	0	f	g	280.0	824
3	b	2783.0	154.0	u	g	w	v	375.0	t	t	5	t	g	100.0	3
4	b	2017.0	5625.0	u	g	w	v	171.0	t	f	0	f	s	120.0	0

A1      object
A2     float64
A3     float64
A4      object
A5      object
A6      object
A7      object
A8     float64
A9      object
A10     object
A11      int64
A12     object
A13     object
A14    float64
A15      int64
dtype: object

catergoicalFeatureNames = ['A1', 'A4', 'A5', 'A6', 'A7', 'A9', 'A10', 'A12', 'A13']
scalarFeatureNames = ['A2', 'A3', 'A8', 'A11', 'A14', 'A15']


    mapper = sklearn_pandas.DataFrameMapper([
            (catergoicalFeatureNames, LabelBinarizer()),
            (scalarFeatureNames,StandardScaler())
            ])

    encoded = mapper.fit_transform(imputedData)
     
```

```
mapper.fit_transform(a)
Traceback (most recent call last):

  File "<ipython-input-51-7c695977a59f>", line 1, in <module>
    mapper.fit_transform(a)

  File "C:\Users\t-hanans\Downloads\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\sklearn\base.py", line 426, in fit_transform
    return self.fit(X, **fit_params).transform(X)

  File "C:\Users\t-hanans\Downloads\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\sklearn_pandas\__init__.py", line 121, in fit
    transformer.fit(self._get_col_subset(X, columns))

  File "C:\Users\t-hanans\Downloads\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\sklearn\preprocessing\label.py", line 306, in fit
    self.classes_ = unique_labels(y)

  File "C:\Users\t-hanans\Downloads\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-packages\sklearn\utils\multiclass.py", line 102, in unique_labels
    raise ValueError("Unknown label type: %r" % ys)

ValueError: Unknown label type: array([[b'b', b'u', b'g', ..., b't', b'f', b'g'],
       [b'a', b'u', b'g', ..., b't', b'f', b'g'],
       [b'a', b'u', b'g', ..., b'f', b'f', b'g'],
       ..., 
       [b'a', b'y', b'p', ..., b't', b't', b'g'],
       [b'b', b'u', b'g', ..., b'f', b'f', b'g'],
       [b'b', b'u', b'g', ..., b'f', b't', b'g']], 
      dtype='|S2')
```

my pip freeze is
```
Cython==0.20.1
Jinja2==2.7.2
MarkupSafe==0.18
Pillow==2.4.0
Polygon==3.0.5
PyOpenGL==3.0.2
PyQtdesignerplugins==1.1
PyQtdoc==4.8.4
PySide==1.2.1
PyWavelets==0.3.0
Pygments==1.6
SQLAlchemy==0.9.4
Scidoc==1.8.0
Sphinx==1.2.2
TTFQuery==1.0.4
VPython==5.74
astroid==1.0.1
brewer2mpl==1.4.1
colorama==0.2.7
cx-Freeze==4.3.2
docutils==0.11
fonttools==2.3
formlayout==1.0.15
ggplot==0.6.5
guidata==1.6.1
guiqwt==2.3.2
h5py==2.2.1
husl==4.0.1
ipython==2.0.0
logilab-common==0.61.0
mahotas==1.1.0
matplotlib==1.3.1
networkx==1.8.1
nose==1.3.1
numexpr==2.3.1
numpy==1.8.1
pandas==0.13.1
patsy==0.2.1
psutil==2.1.0
pyhdf==0.8.3
pylint==1.1.0
pyparsing==2.0.1
pyreadline==2.0
pyscope==py3.3-v2.1.498
pyserial==2.7
python-dateutil==2.2
pytz==2013.9
pywin32==218.5
pyzmq==14.0.1
reportlab==3.0
scikit-image==0.9.3
scikit-learn==0.14.1
scipy==0.13.3
seaborn==0.4.0
simplejson==3.3.3
six==1.6.1
sklearn-pandas==0.0.9
spyder==2.3.1
statsmodels==0.5.0
sympy==0.7.5
tables==3.1.1
tornado==3.2
vispy==0.2.1
winpdb==1.3.6
winpython==1.0
xlrd==0.9.3
```
